---
resource_types:

- name: pull-request
  type: registry-image
  source:
    repository: docker-hub/teliaoss/github-pr-resource
    tag: latest
    aws_region: us-east-1
    aws_access_key_id: ((aws/sts/ecr.access_key))
    aws_secret_access_key: ((aws/sts/ecr.secret_key))
    aws_session_token: ((aws/sts/ecr.security_token))
  tags:
  - resources

- name: github-check
  type: registry-image
  source:
    repository: robojackets/concourse-github-check-resource
    tag: latest
    aws_region: us-east-1
    aws_access_key_id: ((aws/sts/ecr.access_key))
    aws_secret_access_key: ((aws/sts/ecr.secret_key))
    aws_session_token: ((aws/sts/ecr.security_token))
  tags:
  - resources
  defaults:
    commit: ((.:commit))
    repository_url: https://github.com/RoboJackets/loop-workday-upload
    token: (("github.com"/token.token))

- name: github-webhook
  type: registry-image
  source:
    repository: robojackets/concourse-github-webhook-resource
    tag: latest
    aws_region: us-east-1
    aws_access_key_id: ((aws/sts/ecr.access_key))
    aws_secret_access_key: ((aws/sts/ecr.secret_key))
    aws_session_token: ((aws/sts/ecr.security_token))
  tags:
  - resources
  defaults:
    github_token: (("github.com"/token.token))
    webhook_token: ((webhook-token))
    resources:
      loop-workday-upload:
        events:
        - push
        github_uri: https://github.com/RoboJackets/loop-workday-upload
      pull-request:
        events:
        - push
        - pull_request
        github_uri: https://github.com/RoboJackets/loop-workday-upload

resources:

- name: webhooks
  type: github-webhook
  icon: webhook
  public: true
  tags:
  - resources
  check_every: never

- name: loop-workday-upload
  type: git
  icon: github
  public: true
  source:
    branch: main
    password: (("github.com"/token.token))
    uri: https://github.com/RoboJackets/loop-workday-upload
    username: x-access-token
  tags:
  - resources
  check_every: never
  webhook_token: ((webhook-token))

- name: pull-request
  type: pull-request
  icon: source-pull
  public: true
  source:
    repository: RoboJackets/loop-workday-upload
    base_branch: main
    disable_forks: false
    access_token: (("github.com"/token.token))
    v3_endpoint: https://api.github.com
    v4_endpoint: https://api.github.com/graphql
  tags:
  - resources
  check_every: never
  webhook_token: ((webhook-token))

- name: build-check
  type: github-check
  icon: check
  public: true
  source:
    check_name: build
    resource_name: build-check
  tags:
  - resources
  check_every: never

jobs:

- name: build-main
  public: true
  serial: true
  plan:

  - get: loop-workday-upload
    trigger: true

  - load_var: commit
    file: loop-workday-upload/.git/ref
    format: trim
    reveal: true

  - put: build-check
    inputs: []

  - task: poetry-build
    file: loop-workday-upload/.concourse/tasks/poetry-build.yml
    input_mapping:
      source: loop-workday-upload

  - put: webhooks
    no_get: true
    inputs: []

  on_success:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: success
  on_abort:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: cancelled
  on_error:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: action_required
  on_failure:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: failure

- name: build-pull-request
  public: true
  serial: true
  plan:

  - get: pull-request
    trigger: true

  - load_var: commit
    file: pull-request/.git/resource/head_sha
    format: trim
    reveal: true

  - put: build-check
    inputs: []

  - task: poetry-build
    file: pull-request/.concourse/tasks/poetry-build.yml
    input_mapping:
      source: pull-request

  on_success:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: success
  on_abort:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: cancelled
  on_error:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: action_required
  on_failure:
    put: build-check
    no_get: true
    inputs:
    - build-check
    params:
      conclusion: failure
